defaults: &defaults
  host: 127.0.0.1
  port: 27017
  adapter: mongodb

development:
  <<: *defaults
  database: qwikstubs-dev

test: 
  <<: *defaults
  database: qwistubs-test

production:
  uri: <%= ENV['MONGOHQ_URL'] %>
